import { mysqlTable, char, varchar, tinyint, datetime, date, double, int, text, bigint } from "drizzle-orm/mysql-core";

export const patients = mysqlTable("patients", {
  id: char("id", { length: 36 }).primaryKey(),
  patNumber: bigint("pat_number", { mode: "number" }),
  salutation: varchar("salutation", { length: 25 }),
  firstName: varchar("first_name", { length: 100 }),
  lastName: varchar("last_name", { length: 100 }),
  nameTamil: varchar("name_tamil", { length: 150 }),
  sex: char("sex", { length: 6 }),
  birthdate: date("birthdate"),
  registrationAge: int("registration_age"),
  bloodGrp: char("blood_grp", { length: 6 }),
  fatherName: varchar("father_name", { length: 255 }),
  phoneMobile: varchar("phone_mobile", { length: 25 }),
  mobileVerified: tinyint("mobile_verified").default(0),
  phoneHome: varchar("phone_home", { length: 25 }),
  phoneWork: varchar("phone_work", { length: 25 }),
  phoneOther: varchar("phone_other", { length: 25 }),
  emailAddress: varchar("email_address", { length: 255 }),
  primaryAddressStreet: varchar("primary_address_street", { length: 150 }),
  primaryAddressCity: char("primary_address_city", { length: 36 }),
  primaryAddressDistrict: char("primary_address_district", { length: 36 }),
  primaryAddressState: char("primary_address_state", { length: 36 }),
  primaryAddressPostalcode: varchar("primary_address_postalcode", { length: 20 }),
  primaryAddressCountry: char("primary_address_country", { length: 36 }),
  patientGroupId: char("patient_group_id", { length: 36 }),
  patientcategoryId: char("patientcategory_id", { length: 36 }),
  occupationlistId: char("occupationlist_id", { length: 36 }),
  departmentId: char("department_id", { length: 36 }),
  vipPatient: tinyint("vip_patient").default(0),
  vipDescription: text("vip_description"),
  refralId: char("refral_id", { length: 36 }),
  insprovIderId: char("insprovider_id", { length: 36 }),
  parentId: char("parent_id", { length: 36 }),
  parentType: varchar("parent_type", { length: 50 }),
  relationType: varchar("relation_type", { length: 50 }),
  membershipType: varchar("membership_type", { length: 150 }),
  membershipExpiryDate: date("membership_expiry_date"),
  validTill: date("valid_till"),
  regDiscount: int("reg_discount"),
  otherDiscount: int("other_discount"),
  generateBill: tinyint("generate_bill").default(0),
  outstandingAmt: double("outstanding_amt"),
  writeoffAmt: double("writeoff_amt"),
  regDate: date("reg_date"),
  noOfVisit: int("no_of_visit").default(0),
  preferredLang: varchar("preferred_lang", { length: 5 }),
  isAllowWhatsapp: tinyint("is_allow_whatsapp").default(0),
  status: varchar("status", { length: 25 }),
  admissionStatus: varchar("admission_status", { length: 25 }),
  deleted: tinyint("deleted").default(0),
  createdBy: char("created_by", { length: 36 }),
  modifiedUserId: char("modified_user_id", { length: 36 }),
  assignedUserId: char("assigned_user_id", { length: 36 }),
  dateEntered: datetime("date_entered"),
  dateModified: datetime("date_modified"),
});

export const patientimages = mysqlTable("patientimages", {
  id: char("id", { length: 36 }).primaryKey(),
  patientId: char("patient_id", { length: 36 }),
  name: varchar("name", { length: 255 }),
  fileName: varchar("file_name", { length: 255 }),
  fileExtension: varchar("file_extension", { length: 20 }),
  photographType: varchar("photograph_type", { length: 50 }),
  medicategoryId: char("mediacategory_id", { length: 36 }),
  departmentId: char("department_id", { length: 36 }),
  dateUpload: datetime("date_upload"),
  isConsent: tinyint("is_consent").default(0),
  printInReport: tinyint("print_in_report").default(0),
  deleted: tinyint("deleted").default(0),
  dateEntered: datetime("date_entered"),
});
